"""initial schema

Revision ID: c56642d0e0b5
Revises: 
Create Date: 2026-08-18 10:58:50.122768
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c56642d0e0b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.String(length=30), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_table('studies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_version', sa.String(length=64), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expected_seconds', sa.Integer(), nullable=False),
    sa.Column('min_seconds', sa.Integer(), nullable=False),
    sa.Column('max_seconds', sa.Integer(), nullable=False),
    sa.Column('consent_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_status'), 'studies', ['status'], unique=False)
    op.create_table('admin_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_digest', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_sessions_expires_at'), 'admin_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_admin_sessions_session_digest'), 'admin_sessions', ['session_digest'], unique=True)
    op.create_index(op.f('ix_admin_sessions_user_id'), 'admin_sessions', ['user_id'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('study_id', sa.String(length=36), nullable=False),
    sa.Column('variant', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_state'), 'export_jobs', ['state'], unique=False)
    op.create_index(op.f('ix_export_jobs_study_id'), 'export_jobs', ['study_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('study_id', sa.String(length=36), nullable=False),
    sa.Column('participant_code', sa.String(length=32), nullable=False),
    sa.Column('token_digest', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_access_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'participant_code')
    )
    op.create_index(op.f('ix_invites_participant_code'), 'invites', ['participant_code'], unique=False)
    op.create_index(op.f('ix_invites_status'), 'invites', ['status'], unique=False)
    op.create_index(op.f('ix_invites_study_id'), 'invites', ['study_id'], unique=False)
    op.create_index(op.f('ix_invites_token_digest'), 'invites', ['token_digest'], unique=True)
    op.create_table('consent_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invite_id', sa.String(length=36), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['invites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_id', 'policy_version')
    )
    op.create_index(op.f('ix_consent_receipts_invite_id'), 'consent_receipts', ['invite_id'], unique=False)
    op.create_table('participant_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invite_id', sa.String(length=36), nullable=False),
    sa.Column('session_digest', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['invites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_sessions_expires_at'), 'participant_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_participant_sessions_invite_id'), 'participant_sessions', ['invite_id'], unique=False)
    op.create_index(op.f('ix_participant_sessions_session_digest'), 'participant_sessions', ['session_digest'], unique=True)
    op.create_table('recording_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invite_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('original_path', sa.String(length=500), nullable=True),
    sa.Column('normalized_path', sa.String(length=500), nullable=True),
    sa.Column('original_mime', sa.String(length=120), nullable=True),
    sa.Column('original_size', sa.Integer(), nullable=True),
    sa.Column('original_sha256', sa.String(length=64), nullable=True),
    sa.Column('normalized_sha256', sa.String(length=64), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('client_duration_seconds', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('browser_family', sa.String(length=100), nullable=True),
    sa.Column('os_family', sa.String(length=100), nullable=True),
    sa.Column('recorder_settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('qc_status', sa.String(length=20), nullable=False),
    sa.Column('qc_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invite_id'], ['invites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_id', 'attempt_no')
    )
    op.create_index(op.f('ix_recording_attempts_invite_id'), 'recording_attempts', ['invite_id'], unique=False)
    op.create_index(op.f('ix_recording_attempts_qc_status'), 'recording_attempts', ['qc_status'], unique=False)
    op.create_index(op.f('ix_recording_attempts_state'), 'recording_attempts', ['state'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['recording_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_attempt_id'), 'processing_jobs', ['attempt_id'], unique=True)
    op.create_index(op.f('ix_processing_jobs_state'), 'processing_jobs', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_state'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_attempt_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_recording_attempts_state'), table_name='recording_attempts')
    op.drop_index(op.f('ix_recording_attempts_qc_status'), table_name='recording_attempts')
    op.drop_index(op.f('ix_recording_attempts_invite_id'), table_name='recording_attempts')
    op.drop_table('recording_attempts')
    op.drop_index(op.f('ix_participant_sessions_session_digest'), table_name='participant_sessions')
    op.drop_index(op.f('ix_participant_sessions_invite_id'), table_name='participant_sessions')
    op.drop_index(op.f('ix_participant_sessions_expires_at'), table_name='participant_sessions')
    op.drop_table('participant_sessions')
    op.drop_index(op.f('ix_consent_receipts_invite_id'), table_name='consent_receipts')
    op.drop_table('consent_receipts')
    op.drop_index(op.f('ix_invites_token_digest'), table_name='invites')
    op.drop_index(op.f('ix_invites_study_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_status'), table_name='invites')
    op.drop_index(op.f('ix_invites_participant_code'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_export_jobs_study_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_state'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_admin_sessions_user_id'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_session_digest'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_expires_at'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_index(op.f('ix_studies_status'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
